### ISSUE TITLE
"EzPSL allows TLC to show an error trace when an assert fails."

### ISSUE THREAD

**Issue by lemmy** [Calvin-L/ezpsl#1]
Hi Calvin,

"EzPSL allows TLC to show an error trace when an assert fails."  (https://github.com/Calvin-L/ezpsl/blob/master/README.md#comparison-to-pluscal) should have been addressed by https://github.com/tlaplus/tlaplus/issues/461 (https://github.com/tlaplus/tlaplus/commit/19757bdd6aadf7c0e371c40bf591f0d84f12a592).

Cheers,
Markus

**Comment by Calvin-L** [comment]
I've removed that bullet. Thanks for bringing this to my attention; that PlusCal change slipped under my radar and it's a very good one. :)
